config/routes.rb
Rails.application.routes.draw do

  resources :orders

  get 'greetings/hello'

  get 'welcome/index'

  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_and_belongs_to_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  has_and_belongs_to_many :ingredients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/greetings_controller.rb
class GreetingsController < ApplicationController
  def hello
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
    @home_page = true
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    @order.price_cents = 0
    @order.ingredients.each do |t|
      @order.price_cents += t.price
    end
    @order.save!

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.fetch(:order, {}).permit(:address, {:ingredient_ids => []})
    end
end

app/controllers/test_controller_controller.rb
class TestControllerController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

    @ingredients = Ingredient.all

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/greetings_helper.rb
module GreetingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/test_controller_helper.rb
module TestControllerHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/greetings/hello.html.erb
<h1>Greetings#hello</h1>
<p>Find me in app/views/greetings/hello.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HoagieShop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <body class="<%= @home_page ? 'homepage' : ''%>">
      <div class="start">
    <%= yield %>
      </div>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form">
  <h2 class="address">Street Address:</h2>
  <%= f.text_field :address %>

  <h2>Bread:</h2>
  <p class="checkbox"><%= f.collection_check_boxes(:ingredient_ids, Ingredient.where("cat = 'b'"), :id, :name) %></p>


  <h2>Main Ingredients:</h2>
  <p class="checkbox"><%= f.collection_check_boxes(:ingredient_ids, Ingredient.where("cat = 'm'"), :id, :name) %></p>


  <h2>Vegetables:</h2>
   <p class="checkbox"><%= f.collection_check_boxes(:ingredient_ids, Ingredient.where("cat = 'v'"), :id, :name) %></p>


  <h2>Condiments:</h2>
   <p class="checkbox"><%= f.collection_check_boxes(:ingredient_ids, Ingredient.where("cat = 'c'"), :id, :name) %></p>


  <h2>Desert:</h2>
   <p class="checkbox"><%= f.collection_check_boxes(:ingredient_ids, Ingredient.where("cat = 'd'"), :id, :name) %></p>


      <%= f.submit "Buy Hoagie", :class => "btn2" %>
</div>
<% end %>

app/views/orders/edit.html.erb
<h1 class="orderTitle">Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order, class: "btn2" %> |
<%= link_to 'Back', orders_path, class: "btn2" %>

app/views/orders/index.html.erb
<link rel="stylesheet" href="application.css">

<p id="notice"><%= notice %></p>


<h1 class="headline">Hoagie Shop</h1>

<!--
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= order.address %></td>
        <td><%= order.price_cents %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
-->

<br>

<p class="btn"> <%= link_to 'New Order', new_order_path %></p>

app/views/orders/new.html.erb
<h1 class="orderTitle" >New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path, class: "btn2" %> 

app/views/orders/show.html.erb
<p id="notice" class="orderSuccess"><%= notice %></p>

</div>

<div class="receipt">
<h1>Your Order #<%= @order.id %>:</h1>
<ul>
  <% @order.ingredients.each do |ingredient| %>
    <li><%= ingredient.name %></li>
  <% end %>
</ul>

<p>Shipping Address: <%= @order.address %></p>
<p>Total: <%= @order.price_cents / 100.00%>0 €</p>
<%= link_to 'Edit', edit_order_path(@order), class: "btn2" %> 
<%= link_to 'Back', orders_path, class: "btn2" %>
</div>

app/views/welcome/index.html.erb
<h1>Ingredients</h1>
<%-# commented line -%>
<table>
  <tr>
    <th>Name: </th>
    <th>Price: </th>
    <th>Amount: </th>
    <th>Categorie: </th>
  </tr>
<% @ingredients.each do |ingredient| %>
  <tr>
    <td><%= ingredient.name %></td>
    <td><%= ingredient.price %></td>
    <td><%= ingredient.amount %></td>
    <td><%= ingredient.cat %></td>
  </tr>
<% end %>
</table>

app/views/welcome/test.html.erb
<%= form_tag :action => "create" %>
 Name: <%= text_field "item", "name"
%><br />
 Value: <%= text_field "item", "value"
%><br />
 <%= submit_tag %>
<%= end_form_tag %>